import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "../providers";
import { ResponsiveSizes } from "../appshell-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Providers>
        <ResponsiveSizes>
          {children}
        </ResponsiveSizes>
      </Providers>
        
      </body>
    </html>
  );
}
